### ISSUE TITLE
Hey Yangshun

### ISSUE THREAD

**Issue by divyanshu-rawat** [yangshun/facebook-open-source-mentorship-amy-lam#8] opened 2018-04-28 08:20 UTC
I have applied for FB open-source Mentorship program but didn't hear anything from the facebook till so fat.
It's been 1 month since I applied.
Best
Divyanshu

**Comment by yangshun** [comment] 2018-04-30 21:03
Duplicate of https://github.com/facebookmicrosites/fbmentorship/issues/54

**Closed by yangshun** 2018-04-30 21:03 UTC

**Comment by divyanshu-rawat** [comment] 2018-04-30 21:05
@yangshun can you let me know when I will be receiving notification from Facebook regarding open source program.

**Comment by yangshun** [comment] 2018-04-30 21:05
Sorry I'm not a program coordinator, I have no insights about that

**Comment by divyanshu-rawat** [comment] 2018-04-30 21:06
No problem, Thanks a lot.
